visionparams:
    classifier:
       model_path: '/models/classifier_01'

    cascade_classifier:
        path: '/classifier/cascadeNew.xml'

    field_color_detector:
        path: '/config/fieldColor.yaml'

    white_color_detector:
        lower_values: [85, 0, 100]
        upper_values: [255, 100, 255]

    horizon_finder:
        vertical_steps: 30
        horizontal_steps: 30

        precision_pix: 5
        min_precision_pix: 3

    ROS:
        # Subscriber
        img_msg_topic: 'image_raw'
        img_queue_size: 1
        # Publisher
