ball_fcnn_model_path: '/models/fcnn03'
ball_fcnn_debug: false  # only active when true and vision/debug is true, too!
ball_fcnn_threshold: .5  # minimal value for a candidate to be considered
ball_fcnn_expand_stepsize: 4
ball_fcnn_pointcloud_stepsize: 10
ball_fcnn_shuffle_candidate_list: true  # shuffles the list of possible candidate points
ball_fcnn_min_ball_diameter: 5
ball_fcnn_max_ball_diameter: 200

field_color_detector_path: '/config/color_spaces/f031test.yaml'
field_color_detector_use_dummy_green: false
field_color_detector_dummy_lower_values_h: 0
field_color_detector_dummy_lower_values_s: 0
field_color_detector_dummy_lower_values_v: 180
field_color_detector_dummy_upper_values_h: 0
field_color_detector_dummy_upper_values_s: 0
field_color_detector_dummy_upper_values_v: 180

white_color_detector_lower_values_h: 0
white_color_detector_lower_values_s: 0
white_color_detector_lower_values_v: 180
white_color_detector_upper_values_h: 255
white_color_detector_upper_values_s: 140
white_color_detector_upper_values_v: 255

horizon_finder_vertical_steps: 30
horizon_finder_horizontal_steps: 30
horizon_finder_precision_pix: 5
horizon_finder_min_precision_pix: 3

vision_debug: true
vision_ball_classifier: 'fcnn'  # cascade, fcnn or dummy
vision_ball_candidate_horizon_y_offset: 0
vision_ball_candidate_rating_threshold: 0.5

line_detector_horizon_offset: 50
line_detector_linepoints_range: 5000
line_detector_blur_kernel_size: 9

ROS_img_msg_topic: 'image_raw'
ROS_img_queue_size: 1
ROS_ball_msg_topic: 'ball_in_image'
ROS_line_msg_topic: 'line_in_image'

ball_finder_classify_threshold: 0.5
ball_finder_scale_factor: 1.1
ball_finder_min_neighbors: 1
ball_finder_min_size: 10

classifier_model_path: '/models/classifier_01'

cascade_classifier_path: '/classifier/cascadeNew.xml'
