########################
# RoboCup 2022 Bangkok #
########################

# Settings override for the webots simulator field

bitbots_localization:
  ros__parameters:

    #############################
    # Initial pose of the robot #
    #############################

    # Initialize at sideline
    # TODO better parameters
    initial_robot_x1: 2.5
    initial_robot_y1: 3.0
    initial_robot_t1: -1.5
    initial_robot_x2: 2.5
    initial_robot_y2: -3.0
    initial_robot_t2: 1.57

    # Inertial single point position
    initial_robot_x: -2.0
    initial_robot_y: 0.0
    initial_robot_t: 0.0

    ##################
    # Field settings #
    ##################

    # Field size
    field_x: 9.0
    field_y: 6.0

    # Padding
    field_padding: 1.0
