behavior:
  head:
    # Name of the head_behaviors ros-node
    rosnode: head_behavior

    # Sane default values for some modules
    defaults:
      head_mode: 0    # Ball mode

    # Max values for the head position
    max_pan: [-2.35, 2.35]
    max_tilt: [-1.2, 0.2]

    # TODO maybe keep this instead of the generated lines
    # Search pattern for penalty
    #search_pattern_penalty:
    #  - [0, -15]
    #  - [0, -30]
    #  - [30, -7]
    #  - [-30, -7]

    look_at:
        tilt_speed: 6
        pan_speed: 6

    # Search pattern for ball
    search_pattern:
        # Speed search pattern
        tilt_speed: 3
        pan_speed: 3

        # Max values for the search pattern
        pan_max: [135, -135]
        tilt_max: [-10, -60]

        # Number of scan lines for the search pattern
        scan_lines: 2

        # Reduces last scanline by that factor so that robot does not collide
        reduce_last_scanline: 0.2


    # Search pattern for penalty
    search_pattern_penalty:
        tilt_speed: 1
        pan_speed: 2
        pan_max: [-30, 30]
        tilt_max: [-7, -30]
        scan_lines: 2
        reduce_last_scanline: 0.2

    # Search pattern for visual compass features search
    visual_compass_features_pattern:
        tilt_speed: 1
        pan_speed: 1
        pan_max: [-45, 45]
        tilt_max: [7, -7]
        scan_lines: 2

    search_pattern_goal:
        tilt_speed: 1
        pan_speed: 1.5
        pan_max: [135, -135]
        tilt_max: [7, -7]
        scan_lines: 2

    search_pattern_field_features:
        tilt_speed: 3
        pan_speed: 3
        pan_max: [-135, 135]
        tilt_max: [-10, -60]
        scan_lines: 2
        reduce_last_scanline: 0.2

    search_recent_ball:
        tilt_speed: 2
        pan_speed: 2
        offset_pattern: [
            [ 0, 0],
            [ 0, 20],
            [ 0, -20],
            [ 20,-20],
            [ 20, 20],
            [-20, 20],
            [-20,-20],
            [ 40,-20],
        ]
        ball_search_time: 20

    front_search_pattern:
      tilt_speed: 3
      pan_speed: 3
      pan_max: [ 0, 0 ]
      tilt_max: [ -10, -80 ]
      scan_lines: 2
      reduce_last_scanline: 0.2

    # Values for the visual compass record pattern
    record_pattern_scan_lines: 2
    record_pattern_pan_max_left: [-80, 0]
    record_pattern_pan_max_right: [0, -80]
    record_pattern_tilt_max: [14, 0]
    record_pattern_speed_tilt: 1
    record_pattern_speed_pan: 1
    interpolation_steps: 4

    # Visual compass ground truth trigger topic
    visual_compass_trigger_topic: '/visual_compass_ground_truth_trigger'

    # These values describe the minimal required delta between current joint states and target joint states in degrees
    # to reduce unnecessary movement due to noise in the detection of the Ball.
    ball_tracking_min_pan_delta: 1.5
    ball_tracking_min_tilt_delta: 1.5


    # Positions for static head modes
    look_down_position: [0, -65]
    look_forward_position: [0, -7]
    look_up_position: [0, 12]

    # Threshold (in degrees) when a head position is reached and
    # the next position will be triggered
    position_reached_threshold: 5

    # After `ball_lost_time` seconds, the ball is considered lost and will be searched
    ball_lost_time: 0.5
    post_lost_time: 1
