min_frame_step: 16  # ms
min_control_step: 8  # ms


##########
# TOPICS #
##########
clock_topic: "/clock"
server_time_clock_topic: "/server_time_clock"
imu_topic: "imu/data_raw"
imu_head_topic: "imu_head/data"
joint_command_topic: "DynamixelController/command"
joint_states_topic: "joint_states"


##########
# FRAMES #
##########
imu_frame: "imu_frame"
head_imu_frame: "imu_frame_2"