---
# If you want to specify a range instead of a list, you will have to do it in the following way:
# !!python/object/apply:builtins.range [10, 50, 5]

# for settings which are not coverable by ranges or lists you can type "custom"
# This will accept any input and write it to the game_settings.yaml
bot_id:
  options: [1, 2, 3, 4, 5, 6]
  explanation: ""
team_id:
  options: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  explanation: ""
team_color:
  options: [0, 1]
  explanation: "0 is blue, 1 is red"
role:
  options: ['goalie', 'offense', 'defense', 'penalty']
  explanation: ""
position_number:
  options: [0, 1, 2]
  explanation: "0 = center, 1 = left, 2 = right"
