LeftLeg:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin  # kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0001
  kinematics_solver_timeout: 0.01
RightLeg:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin  # kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0001
  kinematics_solver_timeout: 0.01
