dynup:
  engine: 
    engine_rate: {
      type: int,
      description: "",
      default_value: 240,
    }

    end_pose:
      arm_extended_length: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 5.0 ],
        }
      } 
      foot_distance: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 5.0 ],
        }
      } 
      hand_walkready_pitch: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 90.0 ],
        }
      }
      hand_walkready_height: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ -1.0, 1.0 ],
        }
      
      }
      trunk_height: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_pitch: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_x_final: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      arm_side_offset_back: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 5.0 ],
        }
      }

    dynup_back:
      arms_angle_back: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 180.0 ],
        }
      }
      com_shift_1: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      
      }
      com_shift_2: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      foot_angle: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 90.0 ],
        }
      }
      hands_behind_back_x: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      hands_behind_back_z: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      leg_min_length_back: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }        
      }
      time_foot_ground_back: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_full_squat_hands: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_full_squat_legs: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_legs_close: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_height_back: {
        type: double,
        description: "if you decrease this, the robot's ass collides its ankles",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_overshoot_angle_back: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      }
      wait_in_squat_back: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      }

    dynup_front:
      arm_side_offset_front: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      hands_pitch: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ -90.0, 90.0 ],
        }
      }
      leg_min_length_front: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      max_leg_angle: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 90.0 ],
        }
      }
      time_foot_close: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      } 
      time_foot_ground_front: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_hands_front: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_hands_rotate: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_hands_side: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      } 
      time_to_squat: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_torso_45: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_overshoot_angle_front: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ -90.0, 90.0 ],
        }
      }
      trunk_x_front: {
        type: double,
        description: "do not increase this unless you want to burn a fuse",
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      wait_in_squat_front: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      }
      time_walkready: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      } 
    rise: 
      rise_time: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      }

    descend: 
      descend_time: {
        type: double,
        description: "",
        validation: {
          bounds<>: [ 0.0, 5.0 ],
        }
      }

    # stabilizer: # Stabilier
    # stabilizing: False
    # minimal_displacement: False
    # stable_threshold: 0.05
    # stable_duration: 100
    # stabilization_timeout: 2.0

    # # Visualizer
    # spline_smoothness: 100
    # display_debug: True
