dynup:
  engine: 
    engine_rate: {
      type: int,
      description: "",
      default_value: 240,
    }

    end_pose:
      arm_extended_length: {
        type: double,
        description: "",
        default_value: 0.4,
        validation: {
          bounds<>: [ 0.0, 5.0 ],
        }
      } 
      foot_distance: {
        type: double,
        description: "",
        default_value: 0.2,
        validation: {
          bounds<>: [ 0.0, 5.0 ],
        }
      } 
      hand_walkready_pitch: {
        type: double,
        description: "",
        default_value: 40.0,
        validation: {
          bounds<>: [ 0.0, 90.0 ],
        }
      }
      hand_walkready_height: {
        type: double,
        description: "",
        default_value: -0.17,
        validation: {
          bounds<>: [ -1.0, 1.0 ],
        }
      
      }
      trunk_height: {
        type: double,
        description: "",
        default_value: 0.38,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_pitch: {
        type: double,
        description: "",
        default_value: 0.2,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_x_final: {
        type: double,
        description: "",
        default_value: 0.001,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      arm_side_offset_back: {
        type: double,
        description: "",
        default_value: 0.148,
        validation: {
          bounds<>: [ 0.0, 5.0 ],
        }
      }

    dynup_back:
      arms_angle_back: {
        type: double,
        description: "",
        default_value: 120.36,
        validation: {
          bounds<>: [ 0.0, 180.0 ],
        }
      }
      com_shift_1: {
        type: double,
        description: "",
        default_value: 0.051,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      
      }
      com_shift_2: {
        type: double,
        description: "",
        default_value: 0.0,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      foot_angle: {
        type: double,
        description: "",
        default_value: 51.76,
        validation: {
          bounds<>: [ 0.0, 90.0 ],
        }
      }
      hands_behind_back_x: {
        type: double,
        description: "",
        default_value: 0.162,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      hands_behind_back_z: {
        type: double,
        description: "",
        default_value: 0.183,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      leg_min_length_back: {
        type: double,
        description: "",
        default_value: 0.253,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }        
      }
      time_foot_ground_back: {
        type: double,
        description: "",
        default_value: 0.536,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_full_squat_hands: {
        type: double,
        description: "",
        default_value: 0.172,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_full_squat_legs: {
        type: double,
        description: "",
        default_value: 0.196,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_legs_close: {
        type: double,
        description: "",
        default_value: 0.068,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_height_back: {
        type: double,
        description: "if you decrease this, the robot's ass collides its ankles",
        default_value: 0.179,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_overshoot_angle_back: {
        type: double,
        description: "",
        default_value: 5.95,
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      }
      wait_in_squat_back: {
        type: double,
        description: "",
        default_value: 1.0,
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      }

    dynup_front:
      arm_side_offset_front: {
        type: double,
        description: "",
        default_value: 0.13,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      hands_pitch: {
        type: double,
        description: "",
        default_value: -65.86,
        validation: {
          bounds<>: [ -90.0, 90.0 ],
        }
      }
      leg_min_length_front: {
        type: double,
        description: "",
        default_value: 0.244,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      max_leg_angle: {
        type: double,
        description: "",
        default_value: 71.71,
        validation: {
          bounds<>: [ 0.0, 90.0 ],
        }
      }
      time_foot_close: {
        type: double,
        description: "",
        default_value: 0.0,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      } 
      time_foot_ground_front: {
        type: double,
        description: "",
        default_value: 0.132,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_hands_front: {
        type: double,
        description: "",
        default_value: 0.3,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_hands_rotate: {
        type: double,
        description: "",
        default_value: 0.3,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_hands_side: {
        type: double,
        description: "",
        default_value: 0.3,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      } 
      time_to_squat: {
        type: double,
        description: "",
        default_value: 0.924,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      time_torso_45: {
        type: double,
        description: "",
        default_value: 0.462,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      trunk_overshoot_angle_front: {
        type: double,
        description: "",
        default_value: -5.0,
        validation: {
          bounds<>: [ -90.0, 90.0 ],
        }
      }
      trunk_x_front: {
        type: double,
        description: "do not increase this unless you want to burn a fuse",
        default_value: 0.091,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      wait_in_squat_front: {
        type: double,
        description: "",
        default_value: 1.2,
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      }
      time_walkready: {
        type: double,
        description: "",
        default_value: 2.0,
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      } 
    rise: 
      rise_time: {
        type: double,
        description: "",
        default_value: 1.0,
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      }

    descend: 
      descend_time: {
        type: double,
        description: "",
        default_value: 0.25,
        validation: {
          bounds<>: [ 0.0, 5.0 ],
        }
      }

    stabilizer: 
      stabilizing: {
        type: bool,
        description: "",
        default_value: false,
      }
      minimal_displacement: {
        type: bool,
        description: "",
        default_value: false,
      }
      stable_threshold: {
        type: double,
        description: "",
        default_value: 0.05,
        validation: {
          bounds<>: [ 0.0, 1.0 ],
        }
      }
      stable_duration: {
        type: int,
        description: "",
        default_value: 100,
        validation: {
          bounds<>: [ 0, 1000 ],
        }
      }
      stabilization_timeout: {
        type: double,
        description: "",
        default_value: 2.0,
        validation: {
          bounds<>: [ 0.0, 10.0 ],
        }
      }
    
    visualizer: 
      spline_smoothness: {
        type: int,
        description: "",
        default_value: 100,
      }
      display_debug: {
        type: bool,
        description: "",
        default_value: true,
      }

