BBPlanner:
  carrot_distance: 20
  rotation_accuracy: 0.1
  position_accuracy: 0.05
  max_rotation_vel: 0.4
  max_vel_x: 0.25
  min_vel_x: -0.2
  max_vel_y: 0.08
  max_acc: 0.01
  rotation_slow_down_factor: 0.3
  translation_slow_down_factor: 0.6
  orient_to_goal_distance: 1
