BBPlanner:
  carrot_distance: 20
  rotation_accuracy: 0.1
  position_accuracy: 0.05
  max_rotation_vel: 0.7
  max_vel_x: 0.37
  min_vel_x: -0.2
  max_vel_y: 0.12
  rotation_slow_down_factor: 0.3
  translation_slow_down_factor: 0.6
  orient_to_goal_distance: 1
