global_costmap:
  plugins:
    - {name: robot_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: ball_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: keep_out_area, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  # Set map origin to have the origin in the map center
  origin_y: -5.5
  origin_x: -8.0
  robot_base_frame: base_footprint
  global_frame: map

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 1.0
  rolling_window: false
  width: 16.0
  height: 11.0
  robot_radius: 0.2
