local_costmap:
  plugins:
    - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
  # Set map origin to have the origin in the map center
  origin_x: 0
  origin_y: 0
  robot_base_frame: /base_footprint
  global_frame: /map

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 1.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  robot_radius: 0.17

  obstacle_layer:
    enable: true
    observation_sources: obstacles
    obstacles:
        data_type: PointCloud2
        topic: obstacles
        marking: true
        clearing: false
        min_obstacle_height: 0.0
        max_obstacle_height: 100
        obstacle_range: 100
        observation_persistence: 0.0 #only most recent readings