local_costmap:
  plugins:
    - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
  # Set map origin to have the origin in the map center
  origin_x: -5.0
  origin_y: -5.0

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 1.0
  static_map: false
  rolling_window: false
  width: 8.0
  height: 8.0
  robot_radius: 0.17

  obstacle_layer:
    enable: true
    observation_sources: obstacles
    obstacles:
        data_type: PointCloud2
        topic: obstacles
        marking: true
        clearing: true
        min_obstacle_height: 0.0
        max_obstacle_height: 100
        obstacle_range: 100