behavior:
  body:
    roles:
      - "goalie"
      - "offense"
      - "defense"
      - "penalty"

    # Position format as in humanoid_league_msg/Position2D
    #      y
    #      ^       ______________________
    #      |    M  |          |          |  O
    #      |    Y  |_ -x, y   |   x, y  _|  P
    #      |    G  | |        |        | |  P
    # 0    +    O  | |       ( )       | |  G
    #      |    A  |_|        |        |_|  O
    #      |    L  |  -x,-y   |   x,-y   |  A
    #      |       |__________|__________|  L
    #      |
    #      +------------------+--------------> x
    #                         0
    # To be useful for different field sizes, use values in [-1, 1] for x and y

    role_positions:
      goalie: [-0.95, 0]
      defense: [-0.5, 0.5]
      offense: [-0.2, 0]

    # When the ball has not been seen for `ball_lost_time` seconds,
    # it is considered lost and will be searched
    ball_lost_time: 0.5

    # When the ball is closer than `max_kick_distance` meters
    # it is close enough to be kicked
    max_kick_distance: 0.3

    # An area in which the ball can be kicked with the right foot
    # defined by min/max x/y values in meters which represent ball positions relative to base_footprint
    right_kick_min_x: 0
    right_kick_min_y: 0
    right_kick_max_x: 0.15
    right_kick_max_y: 0.2

    # An area in which the ball can be kicked with the left foot
    # defined by min/max x/y values in meters which represent ball positions relative to base_footprint
    left_kick_min_x: -0.15
    left_kick_min_y: 0
    left_kick_max_x: 0
    left_kick_max_y: 0.2

    # defines the radius around the goal (in form of a box)
    # in this area, the goalie will react to the ball.
    # the radius is the margin around the goal to both y and the positive x directions
    ball_dangerous_goal_radius: 1
