/**:
  ros__parameters:
    use_sim_time: True
    engine:
      foot_apex_phase: 0.5
      foot_z_pause: 0.0
      trunk_pause: 0.0
      foot_put_down_phase: 1.0

      kick_length: 0.09
      kick_vel: 0.2
      kick_phase: 0.75

    node:
      engine_freq: 200.0

      ik_timeout: 0.01
      ik_reset: False

      debug_active: False

      max_step_x: 1000.0
      max_step_y: 1000.0
      max_step_xy: 1000.0
      max_step_z: 1000.0
      max_step_angular: 1000.0

      x_speed_multiplier: 1.0
      y_speed_multiplier: 1.0
      yaw_speed_multiplier: 1.0

      imu_active: False
      imu_pitch_threshold: 3.14
      imu_roll_threshold: 3.14
      imu_pitch_vel_threshold: 0.0
      imu_roll_vel_threshold: 0.0
      pause_duration: 0.0

      pressure_phase_reset_active: False
      ground_min_pressure: 0.0
      phase_reset_phase: 0.0
      joint_min_effort: 0.0
      effort_phase_reset_active: False

pid_trunk_fused_pitch:
  ros__parameters:
    p: 0.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0
    i_clamp_min: 0.0
    i_clamp_max: 0.0
    antiwindup: False

pid_trunk_fused_roll:
  ros__parameters:
    p: 0.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0
    i_clamp_min: 0.0
    i_clamp_max: 0.0
    antiwindup: False
