walking:
  engine:
    double_support_ratio: 0.28363568935566663
    foot_rise: 0.09981983461662243
    foot_overshoot_ratio: 0.02615077811854111
    trunk_swing: 0.1006121196444696
    foot_overshoot_phase: 0.7741310415977831
    trunk_height: 0.38441743525632704
    trunk_pitch_p_coef_turn: 0.55143245390492
    trunk_pitch: -0.13582308767933288
    foot_apex_phase: 0.5248171307150776
    trunk_phase: -0.1911105893139

    foot_z_pause: 0.0
    foot_put_down_z_offset: 0.0
    foot_put_down_phase: 1.0
    trunk_x_offset: 0.0
    trunk_y_offset: 0.0
    trunk_pause: 0.0
    trunk_x_offset_p_coef_turn: 0.0
    trunk_x_offset_p_coef_forward: 0.0


    kick_length: 0.09
    kick_vel: 0.2
    kick_phase: 0.75

    first_step_swing_factor: 1.0
    first_step_trunk_phase: -0.5

  node:
    # update frequency of the engine
    engine_freq: 1000.0

    # parameters for bioIK
    ik_timeout: 0.01

    debug_active: True

    trunkYOnlyInDoubleSupport: False

    max_step_x: 0.06
    max_step_y: 0.05
    max_step_xy: 0.09
    max_step_z: 0.45

    vel: -1
    acc: -1
    pwm: -1

    imu_active: False
    imu_pitch_threshold: 0.19
    imu_roll_threshold: 0.4
    imu_pitch_vel_threshold: 1.3
    imu_roll_vel_threshold: 5.7
    pause_duration: 3.0

    publish_odom_tf: False

  pid_trunk_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_fused_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_fused_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_gyro_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_gyro_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_cop_x:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_cop_y:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_ankle_left_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_ankle_right_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_ankle_left_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_ankle_right_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_hip_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_hip_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True