walking:
  engine:
    double_support_ratio: 0.2
    first_step_swing_factor: 0.18
    foot_rise: 0.07
    freq: 1.8
    trunk_phase: -0.2
    trunk_pitch: 0.0
    trunk_pitch_p_coef_forward: 0.5
    trunk_pitch_p_coef_turn: 0.0
    trunk_swing: 0.4
    trunk_x_offset: 0.002
    trunk_y_offset: 0.005
    trunk_z_movement: 0.03
    first_step_trunk_phase: -0.5
    foot_apex_phase: 0.5
    foot_distance: 0.2
    foot_overshoot_phase: 1
    foot_overshoot_ratio: 0.0
    foot_put_down_phase: 1
    foot_z_pause: 0
    trunk_height: 0.4
    trunk_pause: 0

  node:
    # update frequency of the engine
    engine_freq: 200.0

    # parameters for bioIK
    ik_timeout: 0.01

    debug_active: True

    trunkYOnlyInDoubleSupport: False

    # 0.5
    # -0.4
    max_step_x: 10
    # 0.12
    max_step_y: 10
    max_step_xy: 10
    max_step_z: 10
    # 0.5
    max_step_angular: 0.7

    x_speed_multiplier: 1.3
    y_speed_multiplier: 1.3
    yaw_speed_multiplier: 1.5

    vel: -1
    acc: -1
    pwm: -1

    imu_active: False
    imu_pitch_threshold: 0.19
    imu_roll_threshold: 0.4
    imu_pitch_vel_threshold: 1.3
    imu_roll_vel_threshold: 5.7
    pause_duration: 3.0

    phase_reset_active: False
    ground_min_pressure: 1.5
    phase_reset_phase: 0.25
    joint_min_effort: 35
    effort_phase_reset_active: False

  pid_trunk_fused_pitch:
    p: 0.111
    i: 0.01
    d: 0
    i_clamp: 0
    i_clamp_min: -0.25
    i_clamp_max: 0.25
    antiwindup: False
    publish_state: False

  pid_trunk_fused_roll:
    p: 0.111
    i: 0.01
    d: 0
    i_clamp: 0
    i_clamp_min: -0.25
    i_clamp_max: 0.25
    antiwindup: False
    publish_state: False
