/**:
  ros__parameters:
    engine:
      foot_apex_phase: 0.5
      foot_z_pause: 0.0
      trunk_pause: 0.0
      foot_put_down_phase: 1.0

      kick_length: 0.09
      kick_vel: 0.2
      kick_phase: 0.75

    node:
      # update frequency of the engine
      engine_freq: 1000.0

      # parameters for bioIK
      ik_timeout: 0.01
      ik_reset: False

      debug_active: False

      max_step_x: 1000.0
      max_step_y: 1000.0
      max_step_xy: 1000.0
      max_step_z: 1000.0
      max_step_angular: 1000.0

      x_speed_multiplier: 1.0
      y_speed_multiplier: 1.0
      yaw_speed_multiplier: 1.0

      imu_active: False
      imu_pitch_threshold: 0.19
      imu_roll_threshold: 0.4
      imu_pitch_vel_threshold: 1.3
      imu_roll_vel_threshold: 5.7
      pause_duration: 3.0

      pressure_phase_reset_active: False
      ground_min_pressure: 1.5
      phase_reset_phase: 0.25
      joint_min_effort: 35.0
      effort_phase_reset_active: False
