walking:
  engine:
    double_support_ratio: 0.15
    first_step_swing_factor: 1.0
    foot_distance: 0.193
    foot_rise: 0.08
    freq: 1.881
    trunk_height: 0.391
    trunk_phase: -0.225
    trunk_pitch: 0.178
    trunk_pitch_p_coef_forward: 0.205
    trunk_pitch_p_coef_turn: -0.323
    trunk_swing: 0.3
    trunk_x_offset: -0.0256
    trunk_y_offset: 0.0056
    trunk_z_movement: 0.0057
    first_step_trunk_phase: -0.5
    foot_apex_phase: 0.5
    foot_overshoot_phase: 1.0
    foot_overshoot_ratio: 0.0
    foot_put_down_phase: 1.0
    foot_z_pause: 0.0
    trunk_pause: 0.0

    kick_length: 0.09
    kick_vel: 0.2
    kick_phase: 0.75

  node:
    # update frequency of the engine
    engine_freq: 200.0

    # parameters for bioIK
    ik_timeout: 0.01

    debug_active: True

    trunkYOnlyInDoubleSupport: False

    # 0.5
    # -0.4
    max_step_x: 0.18
    # 0.12
    max_step_y: 0.11
    max_step_xy: 0
    max_step_z: 10.05
    # 0.5
    max_step_angular: 0.425

    x_speed_multiplier: 1.33
    y_speed_multiplier: 1.5
    yaw_speed_multiplier: 1.5

    vel: -1
    acc: -1
    pwm: -1

    imu_active: False
    imu_pitch_threshold: 0.19
    imu_roll_threshold: 0.4
    imu_pitch_vel_threshold: 1.3
    imu_roll_vel_threshold: 5.7
    pause_duration: 3.0

    phase_reset_active: False
    ground_min_pressure: 1.5
    phase_reset_phase: 0.25
    joint_min_effort: 35
    effort_phase_reset_active: False

  pid_trunk_fused_pitch:
    p: 2.0
    i: 0.05
    d: 0
    i_clamp: 0
    i_clamp_min: -1.0
    i_clamp_max: 1.0
    antiwindup: False
    publish_state: False

  pid_trunk_fused_roll:
    p: 1.0
    i: 0.1
    d: 0
    i_clamp: 0
    i_clamp_min: -1.0
    i_clamp_max: 1.0
    antiwindup: False
    publish_state: False
