walking:
  engine:
    double_support_ratio: 0.239364560778342
    first_step_swing_factor: 0.531097446843835
    first_step_trunk_phase: -0.206569358297317
    foot_apex_phase: 0.657697582543936
    foot_distance: 0.12355375436617
    foot_overshoot_phase: 0.716463568802289
    foot_overshoot_ratio: 0.641158906043661
    foot_rise: 0.0479718154233863
    freq: 1.49871649909293
    trunk_height: 0.180281689417673
    trunk_phase: -0.0433392346293177
    trunk_pitch: 0.214977418300859
    trunk_pitch_p_coef_forward: -1.97793361353095
    trunk_pitch_p_coef_turn: 2.76832535855566
    trunk_swing: 0.740042320046427
    trunk_x_offset: 0.0164044987875086
    trunk_x_offset_p_coef_forward: -0.288579304971023
    trunk_x_offset_p_coef_turn: -0.6002777540633
    trunk_y_offset: -0.000351105713414536

    foot_z_pause: 0.0
    trunk_pause: 0.0
    foot_put_down_phase: 1.0


    kick_length: 0.09
    kick_vel: 0.2
    kick_phase: 0.75


  node:
    # update frequency of the engine
    engine_freq: 30.0

    # parameters for bioIK
    ik_timeout: 0.01

    debug_active: True

    trunkYOnlyInDoubleSupport: False

    max_step_x: 1000
    max_step_y: 1000
    max_step_xy: 1000
    max_step_z: 1000
    max_step_angular: 1000


    vel: -1
    acc: -1
    pwm: -1

    imu_active: False
    imu_pitch_threshold: 0.19
    imu_roll_threshold: 0.4
    imu_pitch_vel_threshold: 1.3
    imu_roll_vel_threshold: 5.7
    pause_duration: 3.0

    phase_reset_active: False
    ground_min_pressure: 1.5
    phase_reset_phase: 0.25
    joint_min_effort: 35
    effort_phase_reset_active: False

    publish_odom_tf: False

  pid_trunk_fused_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: False

  pid_trunk_fused_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: False
