############
# Feldraum #
############

# Settings override for the f-031 test field

#############################
# Initial pose of the robot #
#############################

# Initialize at sideline
# TODO better parameters
initial_robot_x1: 2.5
initial_robot_y1: 3
initial_robot_t1: -1.5
initial_robot_x2: 2.5
initial_robot_y2: -3
initial_robot_t2: 1.57

# Inertial single point position
initial_robot_x: -2.0
initial_robot_y: 0
initial_robot_t: 0

##################
# Field settings #
##################

# Field size
field_x: 5.45
field_y: 3.88

# Padding
field_padding: 0.7 #0.1
