# Only used locally, the team communication will bind to one of these ports
# and send to the other ports, depending on its bot_id
local_mode: true
local_target_ports:
  - 4001
  - 4002
  - 4003
  - 4004

# Only used if local_mode is false
target_host: 127.0.0.1
target_port: 3737
receive_port: 3737

# Rate of published messages in Hz
rate: 1

# average walking speed in [m/s]
avg_walking_speed: 0.01

# set the color of your team
# 2: red
# 3: blue
# other values are invalid
team_color: 2

#lifetime of data [s]
lifetime: 3

#threshold for necessary belief in data to be send to teammates [0,1]
belief_threshold: 0

# ROS Topics
team_data: 'team_data'
strategy: 'strategy'
robot_state: 'robot_state'
position: 'pose_with_certainty'
ball: 'balls_relative'
obstacles: 'obstacles_relative'
