# Only used if local_mode is false
target_host: 127.0.0.1
target_port: 3737
receive_port: 3737

# Only used when target_host is 127.0.0.1 (local mode)
# the team communication will bind to one of these ports and send to the other ports, depending on its bot_id
local_target_ports:
  - 4001
  - 4002
  - 4003
  - 4004

# Rate of published messages in Hz
rate: 1

# average walking speed in [m/s]
avg_walking_speed: 0.01

# lifetime of data [s]
lifetime: 3

# threshold for necessary belief in data to be send to teammates [0,1]
belief_threshold: 0

# ROS Topics
team_data_topic: 'team_data'
strategy_topic: 'strategy'
pose_topic: 'pose_with_certainty'
ball_topic: 'balls_relative'
obstacles_topic: 'obstacles_relative'
cmd_vel_topic: 'cmd_vel'
gamestate_topic: 'gamestate'
move_base_goal_topic: 'move_base/current_goal'
