# Topics
ball_subscribe_topic: 'balls_relative'
ball_position_publish_topic: 'ball_position_relative_filtered'
ball_movement_publish_topic: 'ball_relative_movement'
ball_publish_topic: 'ball_relative_filtered'

odom_frame: 'odom'

# Time interval of filtering steps in Seconds
filter_time_step: 0.1

process_noise_variance: 0.005
