name: Test if all packages build
on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy

    steps:
      - name: Set up ROS ecosystem
        uses: ros-tooling/setup-ros@v0.7
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Configure git to trust repository
        run: git config --global --add safe.directory /__w/bitbots_meta/bitbots_meta
      - name: Pull our software
        run: make pull-init HTTPS=true
      - name: Install proprietary basler drivers
        run: make basler ARGS="-ci"
      - name: Install packages via rosdep
        run: make rosdep
      - name: Set up colcon workspace
        run: |
          mkdir /colcon_ws/src
          ls -s $(realpath .) /colcon_ws/src/bitbots_meta
      - name: Build packages
        run: |
          . /opt/ros/iron/setup.sh
          colcon build --symlink-install
        working-directory: /colcon_ws
